title: "RFC"
labels: ["RFC"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe what you are trying to achive. You can include proposed solution.
    validations:
      required: true
  - type: textarea
    id: assumptions
    attributes:
      label: 1. General Assumptions
      description: Describe general assumptions for the proposed changes
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: api-changes
    attributes:
      label: 2. API changes
      description: Describe what will change in API.
      value: |
        ### Mutations

        ```graphql

        ```

        ### Types

        ```graphql

        ```
    validations:
      required: false
  - type: textarea
    id: db-changes
    attributes:
      label: 3. Database changes
      description: Describe new models or changes in existing models.
    validations:
      required: false
  - type: textarea
    id: uml-diagrams
    attributes:
      label: 4. UML diagrams
      description: Add UML diagrams that outline the logic behind the changes
      placeholder: |
        ```mermaid

        ```
    validations:
      required: false
  - type: textarea
    id: to-do-list
    attributes:
      label: 5. To Do list
      description: Everything from developer perspective
      placeholder: |
        ```
        ### Tasks
        - [ ] Add a draft title or issue reference here
        ```
    validations:
      required: false
  - type: textarea
    id: to-test
    attributes:
      label: 6. To Test
      description: Put here additional info of what it would be good to check along with new changes.
      placeholder: |
        e.g.:
        - Check feature with tax systems
        - Test with overrode prices
    validations:
      required: false
